dbt_project:
  outputs:
    dev:
      dataset: acidentes
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/matheus/data-engineering/cases/airflow-dbt-bigquery-de-case/include/gcp/service-account.json
      location: US
      method: service-account
      priority: interactive
      project: airflow-dbt-bigquery-de-case
      threads: 1
      type: bigquery
    prd:
      dataset: acidentes
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/service-account.json
      location: US
      method: service-account
      priority: interactive
      project: airflow-dbt-bigquery-de-case
      threads: 1
      type: bigquery
  target: dev
