dbt_project:
  outputs:
    dev:
      dataset: cobli
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/matheus/data-engineering/cases/cobli-mid-data-engineer-case/include/gcp/service-account.json
      location: US
      method: service-account
      priority: interactive
      project: cobli-mid-data-engineer-case
      threads: 1
      type: bigquery
    prd:
      dataset: cobli
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/service-account.json
      location: US
      method: service-account
      priority: interactive
      project: cobli-mid-data-engineer-case
      threads: 1
      type: bigquery
  target: dev
